[package]
name = "sx"
version = "0.1.0"
edition = "2021"
description = "a new kind of parser for `proc_macro`s"
license = "MIT or APACHE 2.0"
repository = "https://github.com/soqb/sx"

[dependencies]

[features]
default = ["attributes"]
attributes = []
