[package]
name = "toy-macros"
description = "a simple test bed & example vermouth macro"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
vermouth = { path = "../../..", features = ["warnings"] }
